require 'pry'
require 'nokogiri'
require 'open-uri'
require 'active_support/core_ext/string/inflections'

require_relative '../lib/apocalypto/utility.rb'
require_relative '../lib/apocalypto/CLI/cli.rb'
require_relative '../lib/apocalypto/CLI/fight.rb'
require_relative '../lib/apocalypto/CLI/shop.rb'
require_relative '../lib/apocalypto/scraper.rb'
require_relative '../lib/apocalypto/player.rb'
require_relative '../lib/apocalypto/country.rb'
require_relative '../lib/apocalypto/zombie.rb'
require_relative '../lib/apocalypto/supply.rb'
require_relative '../lib/apocalypto_app.rb'